### ISSUE TITLE
Resilio Sync 2.6.0

### ISSUE THREAD

**Issue by screendriver** [linuxserver/docker-resilio-sync-armhf#11]
Hi,

Resilio released [v2.6.0](https://help.resilio.com/hc/en-us/articles/360001332150-What-s-new-in-Resilio-Sync-2-6-0). It would be great if you could update this image 👍

**Comment by sparklyballs** [comment]
just pulled latest image and 
root@767f6e2e58dc:/# rslsync -v
Can't accept '-v' as argument

Resilio Sync 2.6 (1317)

**Comment by screendriver** [comment]
Thank you for the very quick answer! I overlooked that this image always references the latest version without any version number 🙄
